# =======================================|  M A X  R E P A I R  C O S T  |==========================================
#        Got an issue to report? Message me on either the discussion page, privately, or submit an issue report on
#        the github page!
#        Please leave a review on the spigot page, it truly helps a lot!
#        Solution developed by geekles
# ===================================================================================================================
# ===================================================================================================================
# The cost of xp levels for repairing a item
# Note this is not the total xp level for repairing both items in the anvil. (Lower Max Repair Cost drops the total)
# Note you can modify the max repair cost for each player with the permission maxrepaircost.limit.#
Default Max Repair Cost: -1
# ====================================================================================================================
# Placeholder item
# Placed in anvil inventory when player can not forge item due to not having enough exp
Placeholder:
  Material: 'GRAY_STAINED_GLASS_PANE'
  ItemMeta:
    Displayname: '&cToo Expensive'
    Lore:
    - '&7&o%player, you have only &2&o%exp&7&oxp'
    Enchanted: false
